### ISSUE TITLE
Continue development? 

### ISSUE THREAD

**Issue by Deftaudio** [AudioMorphology/Europi#2]
Hi, just wondering if you continue developing of this project by adding more features or it's abandoned?

**Comment by AudioMorphology** [comment]
Hi, I stopped development as I wasn't happy with the mechanical attachment of the Pi Zero or the computing power of the Pi Zero at that time. I also needed time (and money) to buy more Eurorack modules - a fully-populated EuroPi can drive 30+ CV and Gate outputs, so I needed more modules to control!

However, now that the Pi 4 Compute Module (CM4) has been released I plan to re-design the hardware to use the CM4, I have one on order and I expect it to arrive next week. 

The form factor is much better for attaching to the rear of a Eurorack module.

I also realised that, for MIDI in, I really needed to bring an interrupt line from the MIDI Minion, because Polling for MIDI messages gave me lots of timing problems. 

So, nothing has happened for a long time, but I hope to be able to start on a new version soon!

Richard

**Comment by Deftaudio** [comment]
Hi Richard, this is great to hear. I've been thinking about Pi based design for quite few years. My idea was to use it mainly for MIDI processing within PD. So with that I can't use custom circuit to drive digital pins without actually writing a full MIDI driver stack. So, as I'm not experienced in that,  I've been thinking on the Teensy+Pi design. in the meantime, with all overhead of the polling mode, this is the approach for low jitter implementation, even consuming lot of Pi cycles.
